/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/game.ts" />
/// <reference path="../scenes/scene2.ts" />
/// <reference path="../scenes/scene3.ts" />
/// <reference path="../scenes/scene4.ts" />
/// <reference path="../scenes/scene5.ts" />
/// <reference path="../scenes/scene6.ts" />
/// <reference path="../scenes/scene7.ts" />
/// <reference path="../scenes/scene8.ts" />
/// <reference path="../scenes/scene9.ts" />
/// <reference path="../scenes/scene10.ts" />
/// <reference path="../scenes/scene11.ts" />
/// <reference path="../scenes/scene12.ts" />
/// <reference path="../scenes/scene13.ts" />
/// <reference path="../scenes/scene14.ts" />
/// <reference path="../scenes/scene15.ts" />
/// <reference path="../scenes/gameover.ts" /> 
//# sourceMappingURL=_reference.js.map